spring:
  server:
    port: 8080
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: ALWAYS

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: 'true'
    generate-ddl: true

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  profiles:
    include: oauth,datasource,recaptcha

